### ISSUE TITLE
Personal info

### ISSUE THREAD

**Issue by ghost** [Ucer/codehaoshi#2]
![image](https://user-images.githubusercontent.com/13285922/30951824-9b2cc8f2-a3ea-11e7-9bf4-e2ca84b10056.png)

**Comment by ghost** [comment]
```codehaoshi/app/Tools/UserMailer.php```


![image](https://user-images.githubusercontent.com/13285922/30951939-22d3d408-a3eb-11e7-91b4-1ca2e079a8b8.png)

**Comment by Ucer** [comment]
45
