### ISSUE TITLE
您好，请问能提供下使用vue的思路吗？

### ISSUE THREAD

**Issue by SnailOwO** [Ucer/codehaoshi#6]
我看了很久的代码，实在没想到您是如何将vue和模板结合起来的，毕竟我看到源代码中也有模板，也有vue,所以有点好奇。我是刚打算学习laravel，自己用过vue。我印象中是，前后分离的话，vue这打包将dist文件夹中的所有编译好的替换到目录下。而这个和我的认知有点不同，能不能帮忙解惑下，谢谢、
、

**Comment by Ucer** [comment]
才看到，请看新项目 https://gitee.com/zhjaa/lucms/settings
